#ifndef QAT_AST_NODE_TYPE_HPP
#define QAT_AST_NODE_TYPE_HPP

namespace qat::ast {

enum class NodeType {
  lib,
  block,
  Break,
  bringEntities,
  bringPaths,
  Continue,
  holder,
  typeDefinition,
  constructorCall,
  functionPrototype,
  functionDefinition,
  memberPrototype,
  memberDefinition,
  convertorPrototype,
  convertorDefinition,
  constructorPrototype,
  constructorDefinition,
  destructorDefinition,
  operatorPrototype,
  operatorDefinition,
  localDeclaration,
  globalDeclaration,
  booleanLiteral,
  integerLiteral,
  unsignedLiteral,
  customIntegerLiteral,
  floatLiteral,
  stringLiteral,
  saySentence,
  ifElse,
  giveSentence,
  defineCoreType,
  closeBox,
  reassignment,
  entity,
  templateEntity,
  plainInitialiser,
  self,
  selfMember,
  selfMemberFunction,
  toConversion,
  unaryExpression,
  ternaryExpression,
  functionCall,
  binaryExpression,
  heapGet,
  heapPut,
  heapGrow,
  memberFunctionCall,
  memberAccess,
  sizeOf,
  sizeOfType,
  memberIndexAccess,
  expressionSentence,
  loopNormal,
  loopTimes,
  loopWhile,
  loopOver,
  loopIndex,
  multithread,
  multithreadGive,
  atomicAssignedExpression,
  nullPointer,
  radixLiteral,
  customFloatLiteral,
  box,
  tupleValue,
  arrayLiteral,
  defineMixType,
  mixTypeInitialiser,
  match,
  defineChoiceType,
  dereference,
  Default,
  newAlias,
  moveExpression,
  typeChecker,
  Not,
  copyExpression,
};

} // namespace qat::ast

#endif