#ifndef QAT_AST_NODE_TYPE_HPP
#define QAT_AST_NODE_TYPE_HPP

namespace qat::ast {

enum class NodeType {
  lib,
  block,
  Break,
  bringEntities,
  bringPaths,
  Continue,
  holder,
  typeDefinition,
  functionPrototype,
  functionDefinition,
  memberPrototype,
  memberDefinition,
  convertorPrototype,
  convertorDefinition,
  constructorPrototype,
  constructorDefinition,
  destructorPrototype,
  destructorDefinition,
  localDeclaration,
  globalDeclaration,
  booleanLiteral,
  integerLiteral,
  unsignedLiteral,
  customIntegerLiteral,
  floatLiteral,
  stringLiteral,
  saySentence,
  ifElse,
  giveSentence,
  exposeBoxes,
  defineCoreType,
  closeBox,
  reassignment,
  entity,
  templateEntity,
  plainInitialiser,
  self,
  selfMember,
  selfMemberFunction,
  toConversion,
  unaryExpression,
  ternaryExpression,
  functionCall,
  binaryExpression,
  heapGet,
  heapPut,
  memberFunctionCall,
  memberAccess,
  sizeOf,
  sizeOfType,
  memberIndexAccess,
  symbol,
  expressionSentence,
  loopNormal,
  loopTimes,
  loopWhile,
  loopOver,
  loopIndex,
  multithread,
  multithreadGive,
  atomicAssignedExpression,
  nullPointer,
  radixLiteral,
  customFloatLiteral,
  box,
  tupleValue,
  arrayLiteral
};

} // namespace qat::ast

#endif