#ifndef QAT_LEXER_TOKEN_TYPE_HPP
#define QAT_LEXER_TOKEN_TYPE_HPP

namespace qat::lexer {

/**
 *  Type of the token recognised by the Lexer.
 * This does not necessarily have to mean anything as
 * far as language semantics goes.
 */
enum class TokenType {
  null  = -1, // null represents an empty value
  FALSE = 0,  // false
  TRUE  = 1,
  startOfFile,
  give,
  Public,
  stop,
  voidType,
  boolType,
  pointerType,
  referenceType,
  unsignedIntegerType,
  integerType,
  floatType,
  stringSliceType,
  cstringType,
  bring,
  from,
  to,
  child,
  external,
  Type,
  model,
  identifier,
  parenthesisOpen,
  parenthesisClose,
  curlybraceOpen,
  curlybraceClose,
  bracketOpen,
  bracketClose,
  colon,
  alias,
  For,
  constant,
  Static,
  Default,
  let,
  assignment,
  associatedAssignment,
  separator,
  integerLiteral,
  unsignedLiteral,
  floatLiteral,
  StringLiteral,
  say,
  as,
  self,
  variationMarker,
  lib,
  box,
  endOfFile,
  expose,
  packed,
  var,
  pointerAccess,
  pointerVariation,
  obtainPointer,
  givenTypeSeparator,
  binaryOperator,
  assignedBinaryOperator,
  If,
  Else,
  heap,
  loop,
  While,
  over,
  sizeOf,
  unaryOperatorLeft,
  unaryOperatorRight,
  lambda,
  comment,
  altArrow,
  bitwiseOr,
  bitwiseAnd,
  bitwiseNot,
  templateTypeStart,
  templateTypeEnd,
  Await,
  Async,
  semiColon,
  ternary,
  isNullPointer,
  isNotNullPointer,
  assignToNullPointer,
  assignToNonNullPointer,
  super,
  variadic,
  Break,
  Continue
};

} // namespace qat::lexer

#endif