name: Build Compiler
on:
  workflow_dispatch:
    inputs:
      version:
        name: "Version"
        required: true
        type: string
      title:
        name: "Title"
        required: true
        type: string

env:
  CI_LIBS_LATEST: https://github.com/qatlang/ci-files/releases/latest/download
  WINDOWS_LIBDIR: D:\a\qat\libs

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List releases
        id: list_releases
        run: echo "release_list=$(gh release list)" >> $GITHUB_OUTPUT
      - name: Create release
        if: ${{ !contains(steps.list_releases.outputs.release_list, inputs.version) }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "v${{ inputs.version }}" --title "v${{ inputs.version }}" --notes "Release notes are updated manually, so it is work in progress" --draft
  linux:
    name: Linux
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: mkdir ../libs

      - name: Update apt cache
        run: sudo apt update

      - name: Install cmake, ninja-build, clang
        run: sudo apt --yes install ninja-build clang-19 lld-19

      - name: Download & setup dependencies for x86_64
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_linux_x86_64.tar.gz
          tar -xzf llvm_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_linux_x86_64.tar.gz
          tar -xzf boost_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_linux_x86_64.tar.gz
          tar -xzf icu4c_linux_x86_64.tar.gz

      - name: CMake configuration for x86_64
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="clang-19" -DCMAKE_CXX_COMPILER="clang++-19" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DTARGET_ARCHITECTURE="x86_64" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DBUILD_SHARED_LIBS=false

      - name: Build project for x86_64
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for x86_64
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-linux-x86_64.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    name: Windows
    needs: [create_release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: |
          New-Item -ItemType Directory -Path ${{ env.WINDOWS_LIBDIR }}

      - name: Download & extract dependencies for x64
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/llvm_windows_x64.tar.gz -OutFile llvm_windows_x64.tar.gz
          7z x -tgzip llvm_windows_x64.tar.gz
          7z x -ttar llvm_windows_x64.tar
          Remove-Item -Path llvm_windows_x64.tar.gz
          Remove-Item -Path llvm_windows_x64.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/boost_windows_x64.tar.gz -OutFile boost_windows_x64.tar.gz
          7z x -tgzip boost_windows_x64.tar.gz
          7z x -ttar boost_windows_x64.tar
          Remove-Item -Path boost_windows_x64.tar.gz
          Remove-Item -Path boost_windows_x64.tar

      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --no-includeRecommended --installWhileDownloading"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: CMake configuration for x64
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLIBS_DIR="${{ env.WINDOWS_LIBDIR }}" -DLLVM_DIR="${{ env.WINDOWS_LIBDIR }}\llvm" -DBOOST_DIR="${{ env.WINDOWS_LIBDIR }}\boost" -DTARGET_ARCHITECTURE="x64" -G"Visual Studio 17 2022" -S ./src -B ./build

      - name: Build project for x64
        run: cmake --build ./build --config Release --parallel 8 --target package

      - name: Install GitHub CLI
        run: choco install gh

      - name: Uploading build for x64
        run: gh release upload "v${{ inputs.version }}" ${{ github.workspace }}\build\qat-${{ inputs.version }}-windows-x64.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove x64 libraries
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          rmdir /s /q llvm
          rmdir /s /q boost
          rmdir /s /q icu4c

      - name: Download and extract dependencies for 32-bit
        run: |
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/llvm_windows_i686.tar.gz -OutFile llvm_windows_i686.tar.gz
          7z x -tgzip llvm_windows_i686.tar.gz
          7z x -ttar llvm_windows_i686.tar
          Remove-Item -Path llvm_windows_i686.tar.gz
          Remove-Item -Path llvm_windows_i686.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/boost_windows_i686.tar.gz -OutFile boost_windows_i686.tar.gz
          7z x -tgzip boost_windows_i686.tar.gz
          7z x -ttar boost_windows_i686.tar
          Remove-Item -Path boost_windows_i686.tar.gz
          Remove-Item -Path boost_windows_i686.tar

      - name: CMake configuration for 32-bit
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLIBS_DIR="${{ env.WINDOWS_LIBDIR }}" -DLLVM_DIR="${{ env.WINDOWS_LIBDIR }}\llvm" -DBOOST_DIR="${{ env.WINDOWS_LIBDIR }}\boost" -DTARGET_ARCHITECTURE="i686" -G"Visual Studio 17 2022" -A Win32 -S ./src -B ./build

      - name: Build project for 32-bit
        run: cmake --build ./build --config Release --parallel 8 --target package

      - name: Uploading build for 32-bit
        run: gh release upload "v${{ inputs.version }}" ${{ github.workspace }}\build\qat-${{ inputs.version }}-windows-i686.zip --clobber

      - name: Remove 32-bit libraries
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          rmdir /s /q llvm
          rmdir /s /q boost
          rmdir /s /q icu4c

      - name: Download and extract dependencies for arm64
        run: |
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/llvm_windows_arm64.tar.gz -OutFile llvm_windows_arm64.tar.gz
          7z x -tgzip llvm_windows_arm64.tar.gz
          7z x -ttar llvm_windows_arm64.tar
          Remove-Item -Path llvm_windows_arm64.tar.gz
          Remove-Item -Path llvm_windows_arm64.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/boost_windows_arm64.tar.gz -OutFile boost_windows_arm64.tar.gz
          7z x -tgzip boost_windows_arm64.tar.gz
          7z x -ttar boost_windows_arm64.tar
          Remove-Item -Path boost_windows_arm64.tar.gz
          Remove-Item -Path boost_windows_arm64.tar

      - name: CMake configuration for arm64
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLIBS_DIR="${{ env.WINDOWS_LIBDIR }}" -DLLVM_DIR="${{ env.WINDOWS_LIBDIR }}\llvm" -DBOOST_DIR="${{ env.WINDOWS_LIBDIR }}\boost" -DTARGET_ARCHITECTURE="arm64" -G"Visual Studio 17 2022" -A ARM64 -S ./src -B ./build

      - name: Build project for arm64
        run: cmake --build ./build --config Release --parallel 8 --target package

      - name: Uploading build for arm64
        run: gh release upload "v${{ inputs.version }}" ${{ github.workspace }}\build\qat-${{ inputs.version }}-windows-arm64.zip --clobber
