name: Build Compiler
on:
  workflow_dispatch:
    inputs:
      version:
        name: 'Version'
        required: true
        type: string
      title:
        name: 'Title'
        required: true
        type: string

env:
  CI_LIBS_LATEST: https://github.com/qatlang/ci-files/releases/latest/download

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List releases
        id: list_releases
        run: echo "release_list=$(gh release list)" >> $GITHUB_OUTPUT
      - name: Create release
        if: ${{ !contains(steps.list_releases.outputs.release_list, inputs.version) }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "v${{ inputs.version }}" --title "v${{ inputs.version }}" --notes "Release notes are updated manually, so it is work in progress" --draft
          

  linux:
    name: Linux
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: mkdir ../libs

      - name: Update apt cache
        run: sudo apt update

      - name: Install cmake, ninja-build, clang
        run: sudo apt --yes install cmake ninja-build clang-19 lld-19

      - name: Download & setup dependencies for x86_64
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_linux_x86_64.tar.gz
          tar -xzf llvm_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_linux_x86_64.tar.gz
          tar -xzf boost_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_linux_x86_64.tar.gz
          tar -xzf icu4c_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/zlib_linux_x86_64.tar.gz
          tar -xzf zlib_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/zstd_linux_x86_64.tar.gz
          tar -xzf zstd_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/libedit_linux_x86_64.tar.gz
          tar -xzf libedit_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/libxml2_linux_x86_64.tar.gz
          tar -xzf libxml2_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/ncurses_linux_x86_64.tar.gz
          tar -xzf ncurses_linux_x86_64.tar.gz

      - name: CMake configuration for x86_64
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="clang-19" -DCMAKE_CXX_COMPILER="clang++-19" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DBUILD_SHARED_LIBS=false

      - name: Build project for x86_64
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for x86_64
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-linux-x86_64.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
