name: Build Compiler
on:
  workflow_dispatch:
    inputs:
      version:
        name: "Version"
        required: true
        type: string
      title:
        name: "Title"
        required: true
        type: string

env:
  CI_LIBS_LATEST: https://github.com/qatlang/ci-files/releases/latest/download
  WINDOWS_LIBDIR: D:\a\qat\libs

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List releases
        id: list_releases
        run: echo "release_list=$(gh release list)" >> $GITHUB_OUTPUT
      - name: Create release
        if: ${{ !contains(steps.list_releases.outputs.release_list, inputs.version) }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "v${{ inputs.version }}" --title "v${{ inputs.version }}" --notes "Release notes are updated manually, so it is work in progress" --draft
  linux:
    if: false
    name: Linux
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: |
          mkdir ../libs
          mkdir ../cmake

      - name: Update apt cache
        run: sudo apt update

      - name: Install cmake, ninja-build, clang
        run: sudo apt --yes install ninja-build clang-19 llvm-19 lld-19

      - name: Download & setup dependencies for x86_64
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_linux_x86_64.tar.gz
          tar -xzf llvm_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_linux_x86_64.tar.gz
          tar -xzf boost_linux_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_linux_x86_64.tar.gz
          tar -xzf icu4c_linux_x86_64.tar.gz
          rm llvm_linux_x86_64.tar.gz
          rm boost_linux_x86_64.tar.gz
          rm icu4c_linux_x86_64.tar.gz

      - name: CMake configuration for x86_64
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="clang-19" -DCMAKE_CXX_COMPILER="clang++-19" -DTARGET_ARCHITECTURE="x86_64" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DBUILD_SHARED_LIBS=false

      - name: Build project for x86_64
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for x86_64
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-linux-x86_64.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove x86_64 libraries
        working-directory: ../libs
        run: |
          rm -rf llvm
          rm -rf boost
          rm -rf icu4c

      - name: Download & extract cmake toolchain files
        working-directory: ../cmake
        run: |
          wget --no-verbose $CI_LIBS_LATEST/cmake_toolchains.tar.gz
          tar -xzf cmake_toolchains.tar.gz
          rm cmake_toolchains.tar.gz

      - name: Install aarch64 toolchain
        run: sudo apt --yes install binutils-aarch64-linux-gnu cpp-14-aarch64-linux-gnu g++-14-aarch64-linux-gnu gcc-14-aarch64-linux-gnu libc6-dev-arm64-cross libc6-arm64-cross libgcc-14-dev-arm64-cross libstdc++6-arm64-cross libstdc++-14-dev-arm64-cross linux-libc-dev-arm64-cross

      - name: Download & setup dependencies for aarch64
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_linux_aarch64.tar.gz
          tar -xzf llvm_linux_aarch64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_linux_aarch64.tar.gz
          tar -xzf boost_linux_aarch64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_linux_aarch64.tar.gz
          tar -xzf icu4c_linux_aarch64.tar.gz
          rm llvm_linux_aarch64.tar.gz
          rm boost_linux_aarch64.tar.gz
          rm icu4c_linux_aarch64.tar.gz

      - name: Clean build directory
        run: rm -rf build/*

      - name: CMake configuration for aarch64
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/../cmake/aarch64.cmake" -DTARGET_ARCHITECTURE="aarch64" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DBUILD_SHARED_LIBS=false

      - name: Build project for aarch64
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for aarch64
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-linux-aarch64.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove aarch64 libraries
        working-directory: ../libs
        run: |
          rm -rf llvm
          rm -rf boost
          rm -rf icu4c

      - name: Install riscv64 toolchain
        run: sudo apt --yes install binutils-riscv64-linux-gnu cpp-14-riscv64-linux-gnu g++-14-riscv64-linux-gnu gcc-14-riscv64-linux-gnu gcc-riscv64-unknown-elf libc6-dev-riscv64-cross libc6-riscv64-cross libgcc-14-dev-riscv64-cross libstdc++6-riscv64-cross libstdc++-14-dev-riscv64-cross libstdc++-14-pic-riscv64-cross linux-libc-dev-riscv64-cross

      - name: Download & setup dependencies for riscv64
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_linux_riscv64.tar.gz
          tar -xzf llvm_linux_riscv64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_linux_riscv64.tar.gz
          tar -xzf boost_linux_riscv64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_linux_riscv64.tar.gz
          tar -xzf icu4c_linux_riscv64.tar.gz
          rm llvm_linux_riscv64.tar.gz
          rm boost_linux_riscv64.tar.gz
          rm icu4c_linux_riscv64.tar.gz

      - name: Clean build directory
        run: rm -rf build/*

      - name: CMake configuration for riscv64
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/../cmake/riscv64.cmake" -DTARGET_ARCHITECTURE="riscv64" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DBUILD_SHARED_LIBS=false

      - name: Build project for riscv64
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for riscv64
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-linux-riscv64.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    name: Windows
    if: false
    needs: [create_release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: |
          New-Item -ItemType Directory -Path ${{ env.WINDOWS_LIBDIR }}

      - name: Download & extract dependencies for x64
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/llvm_windows_x64.tar.gz -OutFile llvm_windows_x64.tar.gz
          7z x -tgzip llvm_windows_x64.tar.gz
          7z x -ttar llvm_windows_x64.tar
          Remove-Item -Path llvm_windows_x64.tar.gz
          Remove-Item -Path llvm_windows_x64.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/boost_windows_x64.tar.gz -OutFile boost_windows_x64.tar.gz
          7z x -tgzip boost_windows_x64.tar.gz
          7z x -ttar boost_windows_x64.tar
          Remove-Item -Path boost_windows_x64.tar.gz
          Remove-Item -Path boost_windows_x64.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/icu4c_windows_x64.tar.gz -OutFile icu4c_windows_x64.tar.gz
          7z x -tgzip icu4c_windows_x64.tar.gz
          7z x -ttar icu4c_windows_x64.tar
          Remove-Item -Path icu4c_windows_x64.tar.gz
          Remove-Item -Path icu4c_windows_x64.tar

      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --no-includeRecommended --installWhileDownloading"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: CMake configuration for x64
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLIBS_DIR="${{ env.WINDOWS_LIBDIR }}" -DLLVM_DIR="${{ env.WINDOWS_LIBDIR }}\llvm" -DBOOST_DIR="${{ env.WINDOWS_LIBDIR }}\boost" -DTARGET_ARCHITECTURE="x64" -G"Visual Studio 17 2022" -S ./src -B ./build

      - name: Build project for x64
        run: cmake --build ./build --config Release --parallel 8 --target package

      - name: Install GitHub CLI
        run: choco install gh

      - name: Uploading build for x64
        run: gh release upload "v${{ inputs.version }}" ${{ github.workspace }}\build\qat-${{ inputs.version }}-windows-x64.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove x64 libraries
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          Remove-Item -Path .\llvm -Force -Recurse
          Remove-Item -Path .\boost -Force -Recurse
          Remove-Item -Path .\icu4c -Force -Recurse

      - name: Clean build directory
        run: |
          Remove-Item -Path .\build -Force -Recurse
          mkdir build

      - name: Download and extract dependencies for 32-bit
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/llvm_windows_i686.tar.gz -OutFile llvm_windows_i686.tar.gz
          7z x -tgzip llvm_windows_i686.tar.gz
          7z x -ttar llvm_windows_i686.tar
          Remove-Item -Path llvm_windows_i686.tar.gz
          Remove-Item -Path llvm_windows_i686.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/boost_windows_i686.tar.gz -OutFile boost_windows_i686.tar.gz
          7z x -tgzip boost_windows_i686.tar.gz
          7z x -ttar boost_windows_i686.tar
          Remove-Item -Path boost_windows_i686.tar.gz
          Remove-Item -Path boost_windows_i686.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/icu4c_windows_i686.tar.gz -OutFile icu4c_windows_i686.tar.gz
          7z x -tgzip icu4c_windows_i686.tar.gz
          7z x -ttar icu4c_windows_i686.tar
          Remove-Item -Path icu4c_windows_i686.tar.gz
          Remove-Item -Path icu4c_windows_i686.tar

      - name: CMake configuration for 32-bit
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLIBS_DIR="${{ env.WINDOWS_LIBDIR }}" -DLLVM_DIR="${{ env.WINDOWS_LIBDIR }}\llvm" -DBOOST_DIR="${{ env.WINDOWS_LIBDIR }}\boost" -DTARGET_ARCHITECTURE="i686" -G"Visual Studio 17 2022" -A Win32 -S ./src -B ./build

      - name: Build project for 32-bit
        run: cmake --build ./build --config Release --parallel 8 --target package

      - name: Uploading build for 32-bit
        run: gh release upload "v${{ inputs.version }}" ${{ github.workspace }}\build\qat-${{ inputs.version }}-windows-i686.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove 32-bit libraries
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          Remove-Item -Path .\llvm -Force -Recurse
          Remove-Item -Path .\boost -Force -Recurse
          Remove-Item -Path .\icu4c -Force -Recurse

      - name: Clean build directory
        run: |
          Remove-Item -Path .\build -Force -Recurse
          mkdir build

      - name: Download and extract dependencies for arm64
        working-directory: ${{ env.WINDOWS_LIBDIR }}
        run: |
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/llvm_windows_arm64.tar.gz -OutFile llvm_windows_arm64.tar.gz
          7z x -tgzip llvm_windows_arm64.tar.gz
          7z x -ttar llvm_windows_arm64.tar
          Remove-Item -Path llvm_windows_arm64.tar.gz
          Remove-Item -Path llvm_windows_arm64.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/boost_windows_arm64.tar.gz -OutFile boost_windows_arm64.tar.gz
          7z x -tgzip boost_windows_arm64.tar.gz
          7z x -ttar boost_windows_arm64.tar
          Remove-Item -Path boost_windows_arm64.tar.gz
          Remove-Item -Path boost_windows_arm64.tar
          Invoke-WebRequest ${{ env.CI_LIBS_LATEST }}/icu4c_windows_arm64.tar.gz -OutFile icu4c_windows_arm64.tar.gz
          7z x -tgzip icu4c_windows_arm64.tar.gz
          7z x -ttar icu4c_windows_arm64.tar
          Remove-Item -Path icu4c_windows_arm64.tar.gz
          Remove-Item -Path icu4c_windows_arm64.tar

      - name: CMake configuration for arm64
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLIBS_DIR="${{ env.WINDOWS_LIBDIR }}" -DLLVM_DIR="${{ env.WINDOWS_LIBDIR }}\llvm" -DBOOST_DIR="${{ env.WINDOWS_LIBDIR }}\boost" -DTARGET_ARCHITECTURE="arm64" -G"Visual Studio 17 2022" -A ARM64 -S ./src -B ./build

      - name: Build project for arm64
        run: cmake --build ./build --config Release --parallel 8 --target package

      - name: Uploading build for arm64
        run: gh release upload "v${{ inputs.version }}" ${{ github.workspace }}\build\qat-${{ inputs.version }}-windows-arm64.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: MacOS
    needs: [create_release]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: |
          mkdir ../libs

      - name: Download & setup dependencies for arm64
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_macos_arm64.tar.gz
          tar -xzf llvm_macos_arm64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_macos_arm64.tar.gz
          tar -xzf boost_macos_arm64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_macos_arm64.tar.gz
          tar -xzf icu4c_macos_arm64.tar.gz
          rm llvm_macos_arm64.tar.gz
          rm boost_macos_arm64.tar.gz
          rm icu4c_macos_arm64.tar.gz

      - name: CMake configuration for arm64
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64" -DTARGET_ARCHITECTURE="arm64" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DBUILD_SHARED_LIBS=false

      - name: Build project for arm64
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for arm64
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-macos-arm64.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove arm64 libraries
        working-directory: ../libs
        run: |
          rm -rf llvm
          rm -rf boost
          rm -rf icu4c

      - name: Download & setup dependencies for x86_64
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_macos_x86_64.tar.gz
          tar -xzf llvm_macos_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_macos_x86_64.tar.gz
          tar -xzf boost_macos_x86_64.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_macos_x86_64.tar.gz
          tar -xzf icu4c_macos_x86_64.tar.gz
          rm llvm_macos_x86_64.tar.gz
          rm boost_macos_x86_64.tar.gz
          rm icu4c_macos_x86_64.tar.gz

      - name: Clean build directory
        run: rm -rf build/*

      - name: CMake configuration for x86_64
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64" -DTARGET_ARCHITECTURE="x86_64" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DBUILD_SHARED_LIBS=false

      - name: Build project for x86_64
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for x86_64
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-macos-x86_64.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove x86_64 libraries
        working-directory: ../libs
        run: |
          rm -rf llvm
          rm -rf boost
          rm -rf icu4c

      - name: Download & setup dependencies for universal (arm64 + x86_64)
        working-directory: ../libs
        run: |
          wget --no-verbose $CI_LIBS_LATEST/llvm_macos_universal.tar.gz
          tar -xzf llvm_macos_universal.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/boost_macos_universal.tar.gz
          tar -xzf boost_macos_universal.tar.gz
          wget --no-verbose $CI_LIBS_LATEST/icu4c_macos_universal.tar.gz
          tar -xzf icu4c_macos_universal.tar.gz
          rm llvm_macos_universal.tar.gz
          rm boost_macos_universal.tar.gz
          rm icu4c_macos_universal.tar.gz

      - name: Clean build directory
        run: rm -rf build/*

      - name: CMake configuration for universal (arm64 + x86_64)
        run: cmake -S src/ -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DTARGET_ARCHITECTURE="universal" -DLIBS_DIR="${{ github.workspace }}/../libs" -DLLVM_DIR="${{ github.workspace }}/../libs/llvm" -DBOOST_DIR="${{ github.workspace }}/../libs/boost" -DBUILD_SHARED_LIBS=false

      - name: Build project for universal (arm64 + x86_64)
        run: cmake --build build --config Release --parallel 8 --target package

      - name: Uploading build for universal (arm64 + x86_64)
        run: gh release upload "v${{ inputs.version }}" ./build/qat-${{ inputs.version }}-macos-universal.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
